spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: chess-book
  datasource:
    url: jdbc:postgresql://localhost:5432/chess-book
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: "/api/${spring.application.name}"
